use_frameworks!

target 'PulseControllerExample' do
  pod 'PulseController', :path => '../'

  target 'PulseControllerExampleTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
