# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.3
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods
- pod repo update
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/PulseControllerExample.xcworkspace -scheme PulseControllerExample -destination "platform=iOS Simulator,name=iPhone 6,OS=11.3" | xcpretty
- pod lib lint
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 2b83ea1c-506e-43ed-9211-aa334f864fcc
